---
title: "Plotly Dashboard 2"
output: 
  html_document:
    code_folding: show
    theme:
      bg: "white"
      fg: "black"
      primary: "steelblue"
      secondary: "forestgreen"
      base_font:
        google: Prompt
      heading_font:
        google: Proza Libre
---

```{r setup, include=FALSE}
if (requireNamespace("thematic")) 
  thematic::thematic_rmd(font = "auto")
```

Another dashboard example uses the \*\*Plotly\*\* package, with data from ggplot2 package illustrating interactive charts with animation button and slider control.

```{r message=FALSE, warning=FALSE}
# install.packages(c("plotly", "tidyverse","scales"))
library(plotly)
library(tidyverse)
library(scales) # use integer for axes
options(scipen = 1) # No scientific notation on axes
#if (interactive()) {
  p <- ggplot(txhousing, aes(month, median)) +
    geom_line(aes(group = year), alpha = 0.3) +
    geom_smooth() +
    geom_line(aes(frame = year, ids = month), color = "red") +
    facet_wrap(~ city, ncol = 8) +
    theme_bw() +
    scale_x_continuous(breaks = pretty_breaks()) +
    ylab("Median") + xlab("Month") +
    theme(text = element_text(family = "Palatino"))
 
  ggplotly(p, width = 900, height = 600) %>%
    animation_opts(1000)
#}

```
