---
title: "Plotly Dashboard"
output: 
  html_document:
    code_folding: show
    theme:
      bg: "white"
      fg: "black"
      primary: "steelblue"
      secondary: "forestgreen"
      base_font:
        google: Prompt
      heading_font:
        google: Proza Libre
---

This dashboard uses the **Plotly** package, with example data and Gapminder data to illustrate interactive charts.  Note the font use, color choices and animation button and slider control.

```{r setup, include=FALSE}

# Set theme for dashboard
# install.packages(c("bslib","thematic"))
library(thematic)
if (requireNamespace("thematic")) 
  thematic::thematic_rmd(font = "auto")
```

```{r message=FALSE}

# install.packages(c("plotly","tidyverse","RColrBrewer"))
library(plotly)
library(tidyverse)
# Reading in example dataset
df <- read.csv("https://plotly.com/~public.health/17.csv", skipNul = TRUE, encoding = "UTF-8")

# Font management
library(showtext)
font_add_google("Cormorant Garamond", "corgaramond")
t <- list(
  family = "corgaramond",
  size = 12)

# Create label function for animation button
labels <- function(size, label) {
  list(
    args = c("xbins.size", size), 
    label = label, 
    method = "restyle"
  )
}

# Create Figure object
fig <- df %>%
  plot_ly(
    x = ~date,
    autobinx = FALSE, 
    autobiny = TRUE, 
    marker = list(color = "steelblue"), 
    name = "date", 
    type = "histogram", 
    xbins = list(
      end = "2016-12-31 12:00", 
      size = "M1", 
      start = "1983-12-31 12:00"
    )
  )

# Configure dropdown menu
fig <- fig %>% layout(
  paper_bgcolor = "white", 
  plot_bgcolor = "white", 
  title = "<b>Shooting Incidents</b><br>use dropdown to change bin size", # HTML to separate line
  xaxis = list(
    type = 'date'
  ),
  yaxis = list(
    title = "Incidents"
  ),
  updatemenus = list(
    list(
      x = 0.1, 
      y = 1.15,
      active = 1, 
      showactive = TRUE,
      buttons = list(
        labels("D1", "Day"),
        labels("M1", "Month"),
        labels("M6", "Half Year"),
        labels("M12", "Year")
      )
    )
  )
)

fig <- fig %>% layout(font = t) # Add font to text

fig


```
```{r  message=FALSE}

#install.packages("gapminder")
library(gapminder)
library(RColorBrewer)
library(plotly)

# Read in Gapminder data
df <- gapminder 

# Font management

t <- list(
  family = "corgaramond",
  size = 12)

# Create figure object
fig <- df %>%
  plot_ly(
    x = ~gdpPercap, 
    y = ~lifeExp,
    size = ~pop, 
    color = ~continent, 
    colors = c("slateblue3", "steelblue", "firebrick", "forestgreen", "turquoise1"), 
        # manually select colar 
    alpha=.5, # translucent glyth
    frame = ~year, 
    text = ~country, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers',
    fill = ~''
  )

# Add font to text
fig <- fig %>% layout(
  xaxis = list(
    type = "log"
  ), font = t
)


fig <- fig %>% layout(legend = list(orientation = "h",   # show entries horizontally
                     xanchor = "center",  # use center of legend as anchor
                     x = 0.5, y = 100))             # put legend in center of x-axis

fig <- fig %>% animation_button(
  x = 1, xanchor = "right", y = 0, yanchor = "bottom"
)
fig <- fig %>% animation_slider(
  currentvalue = list(prefix = "YEAR ", font = list(color="red"))
)
fig


```


