---
title: "Storyboard"
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
---

### Gapminder is based on the Gapminder data



```{r echo=FALSE, message=FALSE}
library(ggplot2)
library(gapminder)

options( scipen = 1 ) # turn off scientific notation with positive value
ggplot(data = gapminder,
            mapping = aes(x = gdpPercap,
                          y = lifeExp, 
                          color = continent)) + 
  geom_point(cex = 1) +
  geom_smooth(method = "loess", color = "red") + scale_x_log10() + 
  xlab("GDP per capita") +
  ylab("Life Expectancy") +
  theme_bw() +
  theme(legend.position = c(.85, .2)) +
  theme(text = element_text(size = 14, family = "Palatino"))

```
   
*** 

This is a sample dashboard design based on flexdashboard sample layout (storyboard).  More detail can be included in the sidebar, explaining the data in chart.

### Happy Planet Index 

```{r}
library(rbokeh)
hpi2016=read.csv("https://raw.githubusercontent.com/datageneration/datavisualization/master/data/hpi2016.csv")
figure(width = 800, height = 600, legend_location = "top_left") %>%
  ly_points(AverageLifeExpectancy, HappyPlanetIndex, data = hpi2016, color = Region, glyph = Region, size = 5, hover = list(Region, GDPPC))

```

### Leaflet 

```{r echo=FALSE, out.width=350}
library(leaflet)
library(maps)

eppsmap <- leaflet() %>% setView(-96.7478372, 32.9886268, zoom=14)

esri <- grep("^Esri", providers, value = TRUE)

for (provider in esri) {
  eppsmap <- eppsmap %>% addProviderTiles(provider, group = provider)
}

find_me_at <- paste(sep = "<br/>",
                  "<b><a href='http://karlho.com' target='_blank'>Karl Ho </a></b>",
                  "<b><a href='http://epps.utdallas.edu' target='_blank'>School of Economic, </a></b>",
                  "<b><a href='http://epps.utdallas.edu' target='_blank'>Political and Policy Sciences</a></b>",
                  "<b><a href='http://www.utdallas.edu' target='_blank'>University of Texsa at Dallas</a></b>",
                  "800 West Campbell Road, GR31",
                  "Richardson TX 75080"
)
eppsmap %>%
  addLayersControl(baseGroups = names(esri),
                   options = layersControlOptions(collapsed = TRUE)) %>%
  # addMiniMap(tiles = esri[[1]], toggleDisplay = TRUE,
  #           position = "bottomleft") %>%
  addMarkers(eppsmap, lng=-96.7478372, lat=32.9886268, popup=find_me_at)  %>%
  htmlwidgets::onRender("
                        function(el, x) {
                        var myMap = this;
                        myMap.on('baselayerchange',
                        function (e) {
                        myMap.minimap.changeLayer(L.tileLayer.provider(e.name));
                        })
                        }")
```

### Base plot 

```{r}
library(RColorBrewer)
plot(pressure, pch=20, col = "firebrick")

```


### D3_Chord diagram

```{r}
knitr::include_url("https://observablehq.com/embed/@d3/chord-diagram?cells=chart", height = "600")
```


***

More space per chart is the advantage of using Storyboard layout.


### D3 Laddar Graph


```{r}
knitr::include_url("https://karlho.github.io/D3/lg_twclimate/index.html", height = "600")
```
